valid_data = {
    "gender": ['male', 'female', 'unisex'],
    "department": ['sales', 'marketing', 'finance', 'hr', 'it', 'operations'],
    "branch": ['online_shop', 'pirozi', 'beheshti', 'narmak'],
    "warehouse_type": ['central', 'in_transit', 'branch', 'defective'],
    "position": ['admin', 'employee', 'technical'],
    "category": ['mobile', 'camera', 'laptop'],
    "markup": [0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
    "discount": [0, 10, 20, 30, 40, 50, 60, 70, 80, 90],

    "mobile_brand": ['nokia', 'samsung', 'apple', 'lg', 'xiaomi', 'huawei'],
    "camera_brand": ['canon', 'samsung', 'nikon', 'fuji', 'sony'],
    "laptop_brand": ['hp', 'lenovo', 'asus', 'dell', 'sony'],
    "mobile_model": ['a05', 'a016', 's24', 'm14', 'iphone14', 'iphone12', 'iphone16'],
    "camera_model": ['EO5', 'Alpha', 'A7r', 'fx30'],
    "laptop_model": ['ideapad', 'vivobook', 'zenbook', 'macbook', 'omen', 'Tuf'],

    "warranty_months": [1, 3, 6, 12, 24, 36],
    "colors": ["red", "blue", "green", "yellow", "black", "white"],
    "screen_size": ['14 inch', '15 inch', '17 inch'],
    "ram": [4, 8, 16, 32, 64, 128],
    "storage": [512, 1024, 2048, 4096],
    "battery_capacity": [12, 13, 14, 15],
    "os": ['android', 'ios', 'windows', 'macos', 'linux'],
    "camera_resolution": ['24MP', '36MP', '48MP'],
    "resolution": ["378PX", "412PX", "414PX", "344px"],
    "processor": ["intel", "amd", "dragon"],
    "sensor_type": ['cmos', 'ccd', 'bsi-cmos'],
    "sensor_size": ["8mm", "10MP"],
    "lens_type": ['prime', 'zoom', 'macro', 'wide-angle', 'telephoto'],
    "lens_mount": ['ef', 'ef-s', 'rf', 'f', 'z', 'e', 'x', 'mft'],
    "iso": ['100', '200', '400', '800', '1600'],
    "shutter_speed": ["1-4", "1-8", "1-15", "1-30", "1-60", "1-250"],
    "video_resolution": ['4k', '1080p', '720p', '480p'],
    "graphics_card": ["intel", "nvidia", "asus"],
    "battery_life": [12, 24, 36, 48],
    "weight": [50, 100, 200],
}
